**Step 1: Data bilan tanishish**
   - CSV faylni ochib, birinchi 10 qatorni ko‘rish. 
   - Column nomlari va sonini tekshirish. 
   - Har bir columndagi missing values sonini aniqlash. 
   - Data turlari (string, numeric, date, json) haqida tushuncha hosil qilish.

In [1]:
import pandas as pd
# CSV faylni ochish
df=pd.read_csv(r'C:\Users\qaleb\Downloads\Telegram Desktop\super_dirty_students.csv')
# birinchi 10 qatorni ko`rish`
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,ninety,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,1603493647,DATA SCIENCE,110,pending,15.5,average,"85,00",1983-04-30T01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18 years,FEMALE,71,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16,data science,NaN,active,0,excellent,275.0,19/11/2004 11:42 PM,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,ninety,8091556011,Matthewfort,avoid,2000.06.26,python,63,active,four point five,excellent,135,1978/09/23,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,twenty,fmale,77,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15,ds,110%,active,15.5,excellent,104 USD,1995-10-20,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11T07:12:29,data_sciense,99,inactive,"3,7",average,"215,00",2014-12-16T06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [2]:
#  columns
df.columns

Index(['student_id', 'name', 'age', 'gender', 'score', 'phone', 'city',
       'email', 'date_of_join', 'course', 'attendance', 'status', 'gpa',
       'remarks', 'money_spent', 'event_time', 'address_raw', 'profile_json'],
      dtype='str')

In [3]:
df.shape

(1000, 18)

In [ ]:
#data frame haqida umumiy malumot
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    1000 non-null   int64
 1   name          665 non-null    str
 2   age           892 non-null    str
 3   gender        781 non-null    str
 4   score         754 non-null    str
 5   phone         629 non-null    str
 6   city          1000 non-null   str
 7   email         849 non-null    str
 8   date_of_join  1000 non-null   str
 9   course        1000 non-null   str
 10  attendance    674 non-null    str
 11  status        1000 non-null   str
 12  gpa           859 non-null    str
 13  remarks       796 non-null    str
 14  money_spent   1000 non-null   str
 15  event_time    1000 non-null   str
 16  address_raw   1000 non-null   str
 17  profile_json  1000 non-null   str
dtypes: int64(1), str(17)
memory usage: 476.6 KB

In [3]:
# missing values number per column
df.isna().sum()

student_id        0
name            335
age             108
gender          219
score           246
phone           371
city              0
email           151
date_of_join      0
course            0
attendance      326
status            0
gpa             141
remarks         204
money_spent       0
event_time        0
address_raw       0
profile_json      0
dtype: int64

In [ ]:
#data typelar haqida malumot
df.dtypes

student_id      int64
name              str
age               str
gender            str
score             str
phone             str
city              str
email             str
date_of_join      str
course            str
attendance        str
status            str
gpa               str
remarks           str
money_spent       str
event_time        str
address_raw       str
profile_json      str
dtype: object

**Step 2: Oddiy string tozalash**
   - Har bir string columnning bo‘sh joylarini olib tashlash (strip). 
   - Bo‘sh stringlarni NaN yoki Null bilan almashtirish.

In [3]:
string_columns=df.select_dtypes(include='str').columns #str columnni topish
df[string_columns]=df[string_columns].apply(lambda x: x.str.strip()) #bo`sh joylarni olib tashlash`
(string_columns=="").sum() #bo`sh str borligini aniqlash

np.int64(0)

In [4]:
# bo`sh strni NaN ga almashtirish
import numpy as np
df.replace("", np.nan, inplace=True)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,$64,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,"3,7",NaN,143,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95,inactive,-2,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110%,active,3.06,average,"238,00",2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,twenty,NaN,ninety,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70,inactive,four point five,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

**Step 3: Raqam va sanalarni tozalash**
   - Age, score, GPA, attendance, money_spent kabi numeric columnlarni tozalash va int yoki float formatiga keltirish. 
   - Date columnlarni pandas datetime formatiga o‘tkazish.

In [5]:
#harflar va keraksiz belgilarni tozalash
numeric_columns=['age', 'score', 'gpa', 'attendance', 'money_spent']
for col in numeric_columns:
    df[col]=(
        df[col]
        .astype(str)
        .str.replace(r"[^\d.\-]", "", regex=True)
    )
#data typeni numeric qilish
for col in numeric_columns:
   df[col]=pd.to_numeric(df[col], errors='coerce')
# intga, floatga o`tkazish
df['age'] = df['age'].astype('Int64')      
df['attendance'] = df['attendance'].astype('Int64')

df['gpa'] = df['gpa'].astype(float)
df['money_spent'] = df['money_spent'].astype(float)

df.dtypes

student_id        int64
name                str
age               Int64
gender              str
score           float64
phone               str
city                str
email               str
date_of_join        str
course              str
attendance        Int64
status              str
gpa             float64
remarks             str
money_spent     float64
event_time          str
address_raw         str
profile_json        str
dtype: object

In [6]:
# date columnlarni pandas datetimega o`tkazish`

df['date_of_join']=pd.to_datetime(df['date_of_join'], format='mixed', errors='coerce')
df['event_time']=pd.to_datetime(df['event_time'], format='mixed', errors='coerce')


df[['date_of_join', 'event_time']]

           date_of_join          event_time
0                   NaT                 NaT
1   2017-08-29 00:00:00 2001-11-10 04:19:00
2   2017-08-14 00:00:00                 NaT
3   1973-09-17 00:00:00                 NaT
4   2023-11-25 00:00:00 2013-10-13 00:00:00
..                  ...                 ...
995 1992-11-13 00:00:00 2007-10-14 18:53:00
996 2024-10-05 00:00:00 2021-06-21 07:46:27
997 2021-11-19 02:23:00 1975-05-11 00:00:00
998                 NaT 2015-05-24 00:00:00
999                 NaT 2015-06-27 08:04:00

[1000 rows x 2 columns]

**Step 4: Email va phone validation **
   - Emaillarni kichik harflarga o‘tkazish va noto‘g‘ri formatdagi emaillarni aniqlash. 
   - Telefon raqamlarni tozalash va yagona standart formatga keltirish (masalan: +998...).

In [73]:
df['email'].head(30)

0                someonegmail.com
1                 psmith@chen.com
2                             NaN
3                         special
4                             six
5         nathangibbs@hotmail.com
6            nguyenlisa@@horn.org
7                           avoid
8           stacysmith@taylor.biz
9        anthonywalker@@gmail.com
10                          stand
11             annalee@@gmail.com
12               someonegmail.com
13     aphillips@holland-diaz.org
14           kevin65@maxwell.info
15                            NaN
16                       yourself
17                          sport
18                           down
19                          voice
20              preid@hotmail.com
21         rrodriguez@@newman.com
22                            NaN
23                            NaN
24        urodriguez@@ferrell.com
25                          about
26                      direction
27    benjamincollins@@davis.info
28          elizabeth49@yahoo.com
29                eolson@carr.net
Name: email, dtype: str

In [7]:
# emaillarni kichik harfga o`tkazdik`
df['email']=df['email'].str.lower()

email_pattern = r'^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
df['email_valid']=df['email'].str.match(email_pattern, na=False)
df['email_valid'].sum()

np.int64(286)

In [8]:
# invalid emaillarni nanga o`zgartirish`
df.loc[~df['email_valid'], 'email']=np.nan

df = df.drop('email_valid', axis=1)
df['email'].head(50)

0                                      NaN
1                          psmith@chen.com
2                                      NaN
3                                      NaN
4                                      NaN
5                  nathangibbs@hotmail.com
6                                      NaN
7                                      NaN
8                    stacysmith@taylor.biz
9                                      NaN
10                                     NaN
11                                     NaN
12                                     NaN
13              aphillips@holland-diaz.org
14                    kevin65@maxwell.info
15                                     NaN
16                                     NaN
17                                     NaN
18                                     NaN
19                                     NaN
20                       preid@hotmail.com
21                                     NaN
22                                     NaN
23                                     NaN
24                                     NaN
25                                     NaN
26                                     NaN
27                                     NaN
28                   elizabeth49@yahoo.com
29                         eolson@carr.net
30                                     NaN
31                                     NaN
32                                     NaN
33                                     NaN
34                                     NaN
35                                     NaN
36                   mccoyandrew@yahoo.com
37                                     NaN
38                                     NaN
39            edgar27@phillips-martin.info
40                                     NaN
41                                     NaN
42                                     NaN
43                                     NaN
44                                     NaN
45           lawrence93@robinson-davis.com
46               wallacerandy@bradshaw.com
47    bartlettchristy@perez-strickland.com
48                                     NaN
49                                     NaN
Name: email, dtype: str

In [9]:
# phone number tozalash

def standardize_phone(x):
    if pd.isna(x):
        return np.nan
    x=str(x)
    x=x.split('x')[0]
    x=''.join(filter(str.isdigit, x))

    if x.startswith('1') and len(x)==11:
        return '+'+x
    elif x.startswith('001') and len(x)>11:
        return '+' + x[2:]
    elif len(x)==10:
        return '+1'+x
    else:
        return np.nan
df['phone_clean']=df['phone'].apply(standardize_phone)
df['phone']=df['phone_clean']
df.drop('phone_clean', axis=1, inplace=True)
df['phone'].head(50)

0     +16193794152
1              NaN
2              NaN
3              NaN
4     +11826595631
5     +10748286016
6     +13140180928
7     +18091556011
8     +18549645423
9     +12054674476
10    +19868509629
11             NaN
12    +12235736311
13             NaN
14             NaN
15             NaN
16             NaN
17    +12425525722
18    +11790996883
19    +16692728730
20             NaN
21    +10388742999
22    +11697150937
23             NaN
24             NaN
25             NaN
26             NaN
27    +14042330292
28    +15211681029
29    +10468929598
30             NaN
31    +10548293587
32    +16180905816
33             NaN
34    +13565523035
35    +18930217782
36    +17731802562
37    +11386481737
38    +15266776949
39             NaN
40             NaN
41             NaN
42    +16981153243
43             NaN
44             NaN
45             NaN
46             NaN
47             NaN
48    +12718094741
49    +10108099177
Name: phone, dtype: str

**Step 5: JSON parsing**
   - JSON columnlarini ochish (profile_json). 
   - JSON ichidagi ma’lumotlarni alohida columnlarga ajratish: hobbies, skills, family, devices. 
   - JSON ichidagi array yoki nested objectlarni tekshirish va flatten qilish.

In [15]:
import ast 
import json
def json_parse(x):
    if pd.isna(x) or x=='':
        return {}
    try:
        return json.loads(x)
    except json.JSONDecodeError:
        try:
            return ast.literal_eval(x)
        except:
            return {}
df['profile_json_parsed'] = df['profile_json'].apply(json_parse)

In [16]:

import copy
df1=copy.deepcopy(df)

In [17]:
df1_flat = pd.json_normalize(
    df1['profile_json_parsed'],
    sep='_'
)
df1_flat

,hobbies,devices,skills_tech_python,skills_tech_excel,skills_tech_sql,skills_soft,family_siblings,family_income_father,family_income_mother
0,"[gun, nice]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[fast, clearly]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0
3,"[left, role]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0
4,"[sort, science]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0
...,...,...,...,...,...,...,...,...,...
995,"[collection, his]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",3.0,5.0,1.0,"[increase, everything]",5.0,1382.0,1335.0
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,"[street, read]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",1.0,4.0,4.0,"[dinner, while]",5.0,1285.0,1005.0
998,"[game, total]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",2.0,2.0,1.0,"[present, cup]",3.0,541.0,571.0
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df1_flat['hobbies']=df1_flat['hobbies'].apply(lambda x: ', '.join(x) if isinstance(x, list) else np.nan)
df1_flat['skills_soft']=df1_flat['skills_soft'].apply(lambda x: ', '.join(x) if isinstance(x, list) else np.nan)

In [19]:
import numpy as np

def extract_devices(devices):
    result = {
        'laptop_brand': np.nan,
        'laptop_year': np.nan,
        'phone_brand': np.nan,
        'phone_year': np.nan
    }
    
    if isinstance(devices, list):
        for d in devices:
            if d.get('type') == 'laptop':
                result['laptop_brand'] = d.get('brand')
                result['laptop_year'] = d.get('year')
            elif d.get('type') == 'phone':
                result['phone_brand'] = d.get('brand')
                result['phone_year'] = d.get('year')
                
    return pd.Series(result)

df1_flat[['laptop_brand','laptop_year','phone_brand','phone_year']] = \
    df1_flat['devices'].apply(extract_devices)

In [20]:
df1_flat

,hobbies,devices,skills_tech_python,skills_tech_excel,skills_tech_sql,skills_soft,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year
0,"gun, nice","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",2.0,5.0,1.0,"with, onto",4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"fast, clearly","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",5.0,3.0,1.0,"despite, clearly",1.0,263.0,202.0,HP,2020.0,Samsung,2023.0
3,"left, role","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",3.0,5.0,1.0,"full, series",4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0
4,"sort, science","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",1.0,4.0,1.0,"whose, save",3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"collection, his","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",3.0,5.0,1.0,"increase, everything",5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,"street, read","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",1.0,4.0,4.0,"dinner, while",5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0
998,"game, total","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",2.0,2.0,1.0,"present, cup",3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df1_flat.drop('devices', axis=1, inplace=True)

In [22]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,profile_json_parsed
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaT,Data Science,<NA>,active,3.72,good,135.0,NaT,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,<NA>,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",{}
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,<NA>,pending,NaN,excellent,185.0,NaT,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,<NA>,inactive,0.00,good,175.0,NaT,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,<NA>,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,<NA>,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,+12050658737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,<NA>,pending,37.00,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,{}
997,998,NaN,20,MALE,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,95,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,+16631181327,Port Rachael,NaN,NaT,data_sciense,110,active,3.06,average,23800.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,<NA>,NaN,NaN,+14867548735,Dariusborough,NaN,NaT,PYTHNO,70,inactive,NaN,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,{}

In [23]:
df.drop('profile_json', axis=1, inplace=True)
df.drop('profile_json_parsed', axis=1, inplace=True)  
df.dtypes

student_id               int64
name                       str
age                      Int64
gender                     str
score                  float64
phone                      str
city                       str
email                      str
date_of_join    datetime64[us]
course                     str
attendance               Int64
status                     str
gpa                    float64
remarks                    str
money_spent            float64
event_time      datetime64[us]
address_raw                str
dtype: object

In [30]:
df=df.join(df1_flat)

In [31]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills_tech_excel,skills_tech_sql,skills_soft,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaT,Data Science,...,5.0,1.0,"with, onto",4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,3.0,1.0,"despite, clearly",1.0,263.0,202.0,HP,2020.0,Samsung,2023.0
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,5.0,1.0,"full, series",4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,4.0,1.0,"whose, save",3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,5.0,1.0,"increase, everything",5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0
996,997,Scott Clark,20,NaN,NaN,+12050658737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,20,MALE,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,4.0,4.0,"dinner, while",5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0
998,999,Brittany Barrett,21,FEMALE,86.0,+16631181327,Port Rachael,NaN,NaT,data_sciense,...,2.0,1.0,"present, cup",3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0
999,1000,NaN,<NA>,NaN,NaN,+14867548735,Dariusborough,NaN,NaT,PYTHNO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Step 6: Address parsing**
  - Address columnni alohida qism va key-larga ajratish: shahar, tuman, pochta kodi. 
  - Raw address columnni saqlab, yangi columnlar hosil qilish (addr_city, addr_district, addr_postal).

In [32]:
df[['address_raw']]
for addr in df['address_raw']:
    print(addr)

Apartment 37, South Kevin district, Tashkent, UZ, 100539
UZ 100332 Tashkent South Patricia
Wendyshire 12-kv, dom 1, Tashkent
Apartment 16, North Tamara district, Tashkent, UZ, 100097
BROKEN,ADDRESS,DATA,,,
Apartment 42, North Jamesfurt district, Tashkent, UZ, 100551
Lake Tracishire 29-kv, dom 8, Tashkent
70576 Butler Harbor Suite 847, Janetberg
Williamsborough 2-kv, dom 18, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 34, North Samantha district, Tashkent, UZ, 100659
Apartment 13, Morrismouth district, Tashkent, UZ, 100315
Frankchester 9-kv, dom 20, Tashkent
UZ 100394 Tashkent Stevensborough
Davidborough 9-kv, dom 29, Tashkent
1965 Jacobs Branch Apt. 418, Timburgh
UZ 100399 Tashkent Joehaven
Apartment 22, Port Kevin district, Tashkent, UZ, 100106
BROKEN,ADDRESS,DATA,,,
Masontown 10-kv, dom 21, Tashkent
BROKEN,ADDRESS,DATA,,,
UZ 100063 Tashkent Lake Shaneland
0451 James Cliffs Suite 725, Wagnermouth
0258 Sean Keys Apt. 380, Kevinfort
06462 Buck Springs Apt. 169, North Lisa
Apartment 20, Lake Crystal district, Tashkent, UZ, 100119
Apartment 27, South David district, Tashkent, UZ, 100696
BROKEN,ADDRESS,DATA,,,
241 Sarah Spring, Bridgetton
Port Robertstad 16-kv, dom 50, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 42, Christineburgh district, Tashkent, UZ, 100686
New Antonio 12-kv, dom 41, Tashkent
UZ 100883 Tashkent West Michaelport
UZ 100652 Tashkent Lake Donaldton
North Amy 11-kv, dom 49, Tashkent
Apartment 49, New Ian district, Tashkent, UZ, 100606
Apartment 22, Youngton district, Tashkent, UZ, 100192
UZ 100766 Tashkent Port William
73317 Timothy Port Suite 163, Dicksonbury
4613 Robert Cliff Suite 875, South Leslie
Apartment 17, Port Kristopherberg district, Tashkent, UZ, 100563
UZ 100515 Tashkent North Joseph
UZ 100297 Tashkent North Candace
Annahaven 19-kv, dom 3, Tashkent
BROKEN,ADDRESS,DATA,,,
UZ 100626 Tashkent East Williamport
6637 Michelle Unions Apt. 959, Erikfort
00607 Alvarez Circles Suite 553, North Benjamin
Apartment 28, East Andrew district, Tashkent, UZ, 100090
UZ 100391 Tashkent Lake Amy
BROKEN,ADDRESS,DATA,,,
UZ 100232 Tashkent Annabury
Christown 6-kv, dom 20, Tashkent
Apartment 40, West Davidhaven district, Tashkent, UZ, 100291
Apartment 42, South Charles district, Tashkent, UZ, 100904
87807 Kayla Glens, Autumnmouth
682 Vasquez Expressway Suite 699, West Nicolechester
Apartment 9, Laurabury district, Tashkent, UZ, 100798
East Elizabethhaven 9-kv, dom 15, Tashkent
6258 Gordon Road, Smithshire
BROKEN,ADDRESS,DATA,,,
9057 Griffin Heights, Rasmussenside
BROKEN,ADDRESS,DATA,,,
Apartment 7, Lutzfort district, Tashkent, UZ, 100220
67890 Conrad Walks, East Tannermouth
BROKEN,ADDRESS,DATA,,,
Apartment 1, North Adammouth district, Tashkent, UZ, 100059
BROKEN,ADDRESS,DATA,,,
Port Lisa 17-kv, dom 46, Tashkent
Benitezmouth 14-kv, dom 38, Tashkent
313 Ayala Point, East Nicholas
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
UZ 100760 Tashkent Millermouth
034 Cooley Way, East Ian
BROKEN,ADDRESS,DATA,,,
UZ 100510 Tashkent Andrewmouth
UZ 100622 Tashkent Aarontown
UZ 100720 Tashkent Lake Hollytown
UZ 100855 Tashkent Lake Tyler
Apartment 18, Tarafurt district, Tashkent, UZ, 100739
BROKEN,ADDRESS,DATA,,,
33084 Williams Point, Jesusborough
BROKEN,ADDRESS,DATA,,,
South Jacobview 25-kv, dom 42, Tashkent
UZ 100240 Tashkent Charlesshire
Apartment 8, South Christina district, Tashkent, UZ, 100031
BROKEN,ADDRESS,DATA,,,
Apartment 15, North Nicholas district, Tashkent, UZ, 100716
East Joshuaton 6-kv, dom 44, Tashkent
BROKEN,ADDRESS,DATA,,,
3646 Micheal Place, Port Douglas
BROKEN,ADDRESS,DATA,,,
902 Wiggins Mill, East Susan
UZ 100535 Tashkent South Jasonfurt
UZ 100126 Tashkent South Teresafurt
BROKEN,ADDRESS,DATA,,,
UZ 100196 Tashkent West Dawnport
4414 Jessica Mountains Apt. 231, Evansfort
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
UZ 100349 Tashkent New Heather
West Billy 17-kv, dom 10, Tashkent
Apartment 32, Port Kyleburgh district, Tashkent, UZ, 100452
New Amber 19-kv, dom 4, Tashkent
30197 Mary Fork, South Brittany
UZ 100223 Tashkent Port David
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Apartment 19, Scotthaven district, Tashkent, UZ, 100170
UZ 100075 Tashkent Boothtown
Apartment 5, Fosterside district, Tashkent, UZ, 100730
9072 Pratt Summit Suite 990, South Jason
BROKEN,ADDRESS,DATA,,,
392 Christopher Center, Port Lindseyfort
Barryborough 13-kv, dom 6, Tashkent
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
55540 Wilson Islands, West Steventon
East Andrewshire 1-kv, dom 31, Tashkent
UZ 100418 Tashkent West Angelafort
BROKEN,ADDRESS,DATA,,,
Apartment 41, Lake Patriciaborough district, Tashkent, UZ, 100625
UZ 100183 Tashkent Padillaborough
1902 William Causeway Apt. 941, South Melissa
Apartment 22, Gillside district, Tashkent, UZ, 100582
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
UZ 100829 Tashkent Robertton
Apartment 50, North Daniel district, Tashkent, UZ, 100874
Apartment 10, Port Brittney district, Tashkent, UZ, 100582
UZ 100820 Tashkent West John
Apartment 40, Jonesborough district, Tashkent, UZ, 100895
BROKEN,ADDRESS,DATA,,,
UZ 100502 Tashkent West Jennifer
Apartment 50, Kimberlychester district, Tashkent, UZ, 100258
UZ 100077 Tashkent Aguilarmouth
Martinmouth 11-kv, dom 16, Tashkent
Apartment 39, Tylerland district, Tashkent, UZ, 100293
Lake Matthew 4-kv, dom 24, Tashkent
6231 Patrick Inlet, North Robertfurt
East Michaelport 23-kv, dom 49, Tashkent
Robertville 11-kv, dom 22, Tashkent
Pamelaborough 22-kv, dom 11, Tashkent
Ewingview 29-kv, dom 16, Tashkent
Port Beth 17-kv, dom 5, Tashkent
579 Alyssa Lake, Port Sarah
815 Maxwell Pike Apt. 262, Eddiemouth
Frankport 5-kv, dom 9, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 14, East Catherinechester district, Tashkent, UZ, 100015
Andersonfort 14-kv, dom 48, Tashkent
19489 Bradford Hill, North Ericchester
BROKEN,ADDRESS,DATA,,,
Apartment 29, New Hannahton district, Tashkent, UZ, 100981
BROKEN,ADDRESS,DATA,,,
Apartment 21, Thomasfurt district, Tashkent, UZ, 100606
795 Martinez Springs, Edwardsshire
3281 Kathleen Court, Port Stephenview
UZ 100220 Tashkent Lake Ronaldshire
Apartment 9, New Mariahton district, Tashkent, UZ, 100768
Apartment 6, South Thomas district, Tashkent, UZ, 100972
BROKEN,ADDRESS,DATA,,,
Apartment 10, Tracyborough district, Tashkent, UZ, 100253
UZ 100234 Tashkent West Michelle
UZ 100959 Tashkent Jamesfurt
New Cheryl 19-kv, dom 6, Tashkent
Apartment 12, Lake Michael district, Tashkent, UZ, 100053
UZ 100683 Tashkent Valentinestad
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
South Paul 12-kv, dom 34, Tashkent
Greeneton 2-kv, dom 50, Tashkent
7357 Kimberly Walks Suite 508, Port Kaylee
Apartment 40, Peterberg district, Tashkent, UZ, 100026
Apartment 15, West Brian district, Tashkent, UZ, 100756
Apartment 12, Davidtown district, Tashkent, UZ, 100617
Apartment 14, Jenniferview district, Tashkent, UZ, 100408
Apartment 14, North Jose district, Tashkent, UZ, 100999
Reevesside 25-kv, dom 20, Tashkent
BROKEN,ADDRESS,DATA,,,
2870 Gamble Fall, Fordview
Apartment 13, Marymouth district, Tashkent, UZ, 100299
540 Gonzalez Junction Apt. 632, Nelsonview
New Sean 1-kv, dom 18, Tashkent
Jonesstad 28-kv, dom 20, Tashkent
BROKEN,ADDRESS,DATA,,,
5846 Erin Glens, Port Kristen
Apartment 28, Jillianview district, Tashkent, UZ, 100658
UZ 100904 Tashkent Xavierton
8258 Kristin Place, Allenview
UZ 100451 Tashkent North Stephanieborough
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
New Josephville 1-kv, dom 23, Tashkent
Michaelborough 6-kv, dom 31, Tashkent
BROKEN,ADDRESS,DATA,,,
UZ 100922 Tashkent East Nicholas
094 Mark Fork, Matthewmouth
Charlesburgh 23-kv, dom 41, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 42, Smithborough district, Tashkent, UZ, 100017
00705 Terrance Street Apt. 121, Christinaport
UZ 100020 Tashkent South Anthony
UZ 100583 Tashkent Robertmouth
Meaganchester 4-kv, dom 34, Tashkent
8175 Davis Mountains, Lake James
Apartment 38, Rachelport district, Tashkent, UZ, 100706
Apartment 27, New Brianshire district, Tashkent, UZ, 100123
UZ 100413 Tashkent Perryhaven
3347 Huff Flats Suite 397, South Juliantown
31066 Alejandro Terrace Apt. 105, Faithhaven
UZ 100852 Tashkent Lake Samantha
Apartment 27, West Pamelafurt district, Tashkent, UZ, 100776
Apartment 47, South Joshuabury district, Tashkent, UZ, 100368
BROKEN,ADDRESS,DATA,,,
UZ 100054 Tashkent Munozshire
Apartment 27, South Lauren district, Tashkent, UZ, 100652
New Jason 27-kv, dom 49, Tashkent
388 Jonathan Tunnel, Claytontown
1104 Sanchez Locks Apt. 466, Jonesberg
UZ 100469 Tashkent Samanthaborough
BROKEN,ADDRESS,DATA,,,
UZ 100020 Tashkent New Danaburgh
Apartment 1, Webbburgh district, Tashkent, UZ, 100201
BROKEN,ADDRESS,DATA,,,
685 Tiffany Island Apt. 341, Adamhaven
7335 Alex Parks Apt. 827, Gordontown
Port Bradleyfurt 3-kv, dom 15, Tashkent
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
2195 Hamilton Turnpike Apt. 662, Gutierrezchester
BROKEN,ADDRESS,DATA,,,
Apartment 4, Riddleshire district, Tashkent, UZ, 100048
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Apartment 24, East Pamelafurt district, Tashkent, UZ, 100917
BROKEN,ADDRESS,DATA,,,
Apartment 38, Lake Amychester district, Tashkent, UZ, 100854
55355 Lucero Manors Suite 542, East Michaelhaven
Apartment 35, West Ericborough district, Tashkent, UZ, 100678
Johntown 7-kv, dom 50, Tashkent
Allisonfurt 7-kv, dom 13, Tashkent
Joseborough 23-kv, dom 30, Tashkent
East Taylor 8-kv, dom 23, Tashkent
UZ 100410 Tashkent Adkinsborough
87498 Haynes Wall Suite 838, South Rachel
Apartment 25, New John district, Tashkent, UZ, 100658
BROKEN,ADDRESS,DATA,,,
Andersonland 15-kv, dom 10, Tashkent
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Apartment 27, New Mark district, Tashkent, UZ, 100999
Johnview 8-kv, dom 27, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 43, Sarahstad district, Tashkent, UZ, 100781
UZ 100304 Tashkent Jonesfurt
North Alicia 20-kv, dom 35, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 29, North Tyroneville district, Tashkent, UZ, 100883
UZ 100588 Tashkent West Elizabeth
Apartment 17, North Raymond district, Tashkent, UZ, 100376
63287 Donna Walk, Savageborough
Apartment 20, Lake Stacy district, Tashkent, UZ, 100919
42654 Obrien Stream Apt. 484, North Ianberg
0553 Joseph Crest, Port Stephenchester
UZ 100416 Tashkent Lake John
Apartment 20, Rileyside district, Tashkent, UZ, 100580
2917 Connie Motorway, West Jamie
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
UZ 100679 Tashkent Maryport
Apartment 8, Ashleyborough district, Tashkent, UZ, 100060
4741 Phillips Course Apt. 019, Lake Theresafurt
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
978 Allison Loop Apt. 882, Whitemouth
BROKEN,ADDRESS,DATA,,,
South David 8-kv, dom 24, Tashkent
UZ 100578 Tashkent New Davidmouth
Curryhaven 5-kv, dom 5, Tashkent
86909 Nguyen Views, Hernandezchester
UZ 100382 Tashkent Morenoview
96315 Annette Rest, Port Charlesport
Apartment 35, Huffburgh district, Tashkent, UZ, 100573
Port Karenborough 15-kv, dom 2, Tashkent
West Josephville 28-kv, dom 45, Tashkent
UZ 100431 Tashkent Garciafort
Apartment 31, Lake Karen district, Tashkent, UZ, 100697
36436 Gamble Freeway Suite 098, Jeanstad
BROKEN,ADDRESS,DATA,,,
5327 Anthony Rest, Russellfort
780 William Summit Apt. 320, Shawnstad
Apartment 19, North Teresaberg district, Tashkent, UZ, 100009
410 Baker Cliffs, South Ian
Apartment 50, Johnsonfurt district, Tashkent, UZ, 100029
663 Cook Lodge Apt. 565, Yustad
UZ 100024 Tashkent West Jessicafurt
BROKEN,ADDRESS,DATA,,,
Christopherhaven 7-kv, dom 45, Tashkent
Apartment 44, Jonesmouth district, Tashkent, UZ, 100100
1120 Brittany Cliffs Suite 826, New Jordan
10040 West Lakes Suite 279, East Samanthaland
UZ 100076 Tashkent Port Lauren
Michaelburgh 6-kv, dom 30, Tashkent
Sharonland 2-kv, dom 45, Tashkent
Murraymouth 19-kv, dom 29, Tashkent
Apartment 15, Pittmanchester district, Tashkent, UZ, 100280
02174 Jennifer Greens Apt. 839, Morenomouth
BROKEN,ADDRESS,DATA,,,
New Charles 14-kv, dom 1, Tashkent
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
6771 Miller Crescent, Port Sarah
Apartment 25, New Dawnburgh district, Tashkent, UZ, 100666
Apartment 19, East Connie district, Tashkent, UZ, 100047
316 Elizabeth Run, South Jamesport
BROKEN,ADDRESS,DATA,,,
UZ 100190 Tashkent North Miranda
West Robertburgh 4-kv, dom 9, Tashkent
Apartment 11, Port Calebtown district, Tashkent, UZ, 100670
UZ 100074 Tashkent New Rodney
607 Torres Brook Suite 210, South Joy
UZ 100700 Tashkent Shaunfort
BROKEN,ADDRESS,DATA,,,
West Patrickberg 13-kv, dom 41, Tashkent
South Kylebury 23-kv, dom 5, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 15, North Angela district, Tashkent, UZ, 100462
Apartment 4, Thomasport district, Tashkent, UZ, 100098
UZ 100264 Tashkent Williamsmouth
UZ 100563 Tashkent East Nicole
BROKEN,ADDRESS,DATA,,,
Jessicaton 1-kv, dom 15, Tashkent
BROKEN,ADDRESS,DATA,,,
Apartment 36, Glennmouth district, Tashkent, UZ, 100438
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Coltonborough 27-kv, dom 21, Tashkent
UZ 100226 Tashkent Port Jimmyberg
North Scott 5-kv, dom 9, Tashkent
Apartment 24, West James district, Tashkent, UZ, 100774
BROKEN,ADDRESS,DATA,,,
655 Angelica Plaza Suite 842, Hickshaven
955 Matthew Row, Angelaside
3169 Brenda Place Suite 788, North Theodore
UZ 100049 Tashkent New Wendymouth
UZ 100250 Tashkent Wallacechester
Apartment 29, South Anna district, Tashkent, UZ, 100327
Jonathanmouth 26-kv, dom 24, Tashkent
Apartment 41, East George district, Tashkent, UZ, 100734
134 Katelyn Alley Apt. 071, New William
36856 Robert Plains Suite 752, East Christineshire
3869 Mary Plains, Michaelfort
UZ 100431 Tashkent North Elizabeth
9044 Patterson Shoal, East Thomas
Madelineborough 29-kv, dom 49, Tashkent
UZ 100288 Tashkent Calebburgh
Apartment 33, South Amy district, Tashkent, UZ, 100877
BROKEN,ADDRESS,DATA,,,
UZ 100186 Tashkent North Timothyside
UZ 100148 Tashkent North Josephview
42338 Stewart Mission Apt. 356, Lisamouth
BROKEN,ADDRESS,DATA,,,
996 Kerr Alley Apt. 067, Christophermouth
Apartment 1, Jerryville district, Tashkent, UZ, 100129
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
20130 Clifford Manor, Michaelmouth
48963 Jones Summit, East Jillstad
69350 Logan Gardens, Davidland
Apartment 28, Juanhaven district, Tashkent, UZ, 100382
Gutierrezchester 4-kv, dom 8, Tashkent
Apartment 16, West Glenn district, Tashkent, UZ, 100309
015 Claudia Fort, Nicolehaven
Apartment 11, Cardenasport district, Tashkent, UZ, 100181
Johnbury 21-kv, dom 30, Tashkent
79649 Drake Locks, Anthonymouth
West Haleyton 6-kv, dom 8, Tashkent
Apartment 10, Mcclureborough district, Tashkent, UZ, 100854
4387 Schultz Ville Suite 145, Port Candaceland
UZ 100279 Tashkent Smithton
BROKEN,ADDRESS,DATA,,,
Apartment 29, Deniseview district, Tashkent, UZ, 100684
Amandaview 11-kv, dom 34, Tashkent
Apartment 46, Williamsview district, Tashkent, UZ, 100561
New Steven 4-kv, dom 23, Tashkent
Apartment 17, Johnsonburgh district, Tashkent, UZ, 100810
Apartment 18, Jonathantown district, Tashkent, UZ, 100374
16728 Villa Way Suite 288, North Cody
8989 Wesley Prairie Suite 040, Lake Paulfort
4018 Hutchinson Camp Apt. 954, Lake Michelleport
Wayneland 15-kv, dom 40, Tashkent
36971 Christine Meadow, Ashleytown
Apartment 20, Port David district, Tashkent, UZ, 100754
East Philipport 26-kv, dom 1, Tashkent
Lake Michael 24-kv, dom 22, Tashkent
Apartment 9, Port William district, Tashkent, UZ, 100656
Kimberlyside 28-kv, dom 26, Tashkent
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Apartment 27, New Patricia district, Tashkent, UZ, 100235
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
UZ 100910 Tashkent New Joseph
6421 Lane Falls Apt. 045, East Deborahport
UZ 100809 Tashkent East Michaelhaven
East Jasonstad 26-kv, dom 14, Tashkent
BROKEN,ADDRESS,DATA,,,
UZ 100155 Tashkent Lake Lukeland
UZ 100507 Tashkent Lake Jodiview
Port Catherinemouth 29-kv, dom 47, Tashkent
28439 Frances Extension Suite 697, Ronaldburgh
791 Norma Fork, Port Garyport
Apartment 49, Wallshire district, Tashkent, UZ, 100522
BROKEN,ADDRESS,DATA,,,
Apartment 23, East Chad district, Tashkent, UZ, 100316
UZ 100174 Tashkent Michaeltown
BROKEN,ADDRESS,DATA,,,
UZ 100113 Tashkent North Roy
Apartment 44, Smithshire district, Tashkent, UZ, 100091
UZ 100144 Tashkent Lake Dawnside
Apartment 47, East Michele district, Tashkent, UZ, 100025
UZ 100116 Tashkent Jamesfort
Gibsonhaven 7-kv, dom 6, Tashkent
UZ 100395 Tashkent West Jasonport
BROKEN,ADDRESS,DATA,,,
UZ 100323 Tashkent North Tracyport
32167 Phillips Expressway, Lake Brittany
Apartment 49, New William district, Tashkent, UZ, 100630
Apartment 50, Port Hannahchester district, Tashkent, UZ, 100469
New Andreaton 3-kv, dom 49, Tashkent
East Melissa 19-kv, dom 44, Tashkent
Kathleenchester 19-kv, dom 10, Tashkent
Apartment 32, Tammychester district, Tashkent, UZ, 100928
721 Ball Camp Suite 246, Hernandeztown
Apartment 44, East Michele district, Tashkent, UZ, 100459
5951 Richard Common, Wilsonview
BROKEN,ADDRESS,DATA,,,
39753 Emily Harbors, North Danielleview
UZ 100447 Tashkent New Kevin
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Lake David 11-kv, dom 11, Tashkent
BROKEN,ADDRESS,DATA,,,
UZ 100779 Tashkent Sophiashire
South Jonathanview 11-kv, dom 15, Tashkent
UZ 100680 Tashkent Cartermouth
11041 Kristen Mountain, Stewartshire
New Katherine 17-kv, dom 14, Tashkent
BROKEN,ADDRESS,DATA,,,
UZ 100349 Tashkent Bryantmouth
4044 Ashley Canyon Suite 093, Eugenebury
Apartment 31, New Tristanstad district, Tashkent, UZ, 100639
37125 Harris Ridges, Feliciahaven
Apartment 17, East Melanieton district, Tashkent, UZ, 100892
6619 Mills Island Suite 519, East Richard
82258 Ward Vista, Trevorport
Apartment 17, Davidview district, Tashkent, UZ, 100309
59092 Strickland Road Apt. 407, Torresville
49187 Holland Crossing Apt. 560, Valenzuelachester
BROKEN,ADDRESS,DATA,,,
Apartment 42, South Robertchester district, Tashkent, UZ, 100965
Apartment 18, West Javierborough district, Tashkent, UZ, 100982
Apartment 8, Brownberg district, Tashkent, UZ, 100457
New Chris 4-kv, dom 21, Tashkent
South Vickieport 14-kv, dom 38, Tashkent
Port Christineton 29-kv, dom 1, Tashkent
BROKEN,ADDRESS,DATA,,,
BROKEN,ADDRESS,DATA,,,
Apartment 45, Wilsonmouth district, Tashkent, UZ, 100904
386 Stanley Club Suite 051, West Dawn
BROKEN,ADDRESS,DATA,,,
UZ 100575 Tashkent Peterland
UZ 100278 Tashkent New Calvinstad
Apartment 30, Lake Johnland district, Tashkent, UZ, 100801
72389 Schmidt Place Apt. 885, South Patrickshire
495 Ochoa Extensions, East Alexander
127 Wong Locks, South Sarah
Apartment 9, Cochranland district, Tashkent, UZ, 100971
BROKEN,ADDRESS,DATA,,,
Port Jayton 7-kv, dom 3, Tashkent
80592 Wiley Views Suite 243, East Thomasville
North James 7-kv, dom 5, Tashkent
Apartment 30, North Kimberlymouth district, Tashkent, UZ, 100183
38022 Theresa Highway Suite 457, East Markbury
UZ 100134 Tashkent Fitzgeraldside
UZ 100401 Tashkent Port Christopher
655 Hughes Rapid Suite 623, New Kevin
Apartment 2, Bakerhaven district, Tashkent, UZ, 100284
27108 Mark Ranch, Jenniferchester
89583 Crawford Crescent, Port William
47640 Lambert Camp Apt. 309, Port Keithport
847 Thompson Fall Suite 006, Pooleburgh
UZ 100612 Tashkent New Catherinemouth
Apartment 8, Lake Gregory district, Tashkent, UZ, 100234
Carrieside 11-kv, dom 25, Tashkent
West Lindaburgh 28-kv, dom 1, Tashkent
UZ 100704 Tashkent South Breannaview
Port Jose 5-kv, dom 24, Tashkent
Apartment 46, Rickyport district, Tashkent, UZ, 100191
UZ 100167 Tashkent New Aaron
Reyesfurt 8-kv, dom 19, Tashkent
Davisville 14-kv, dom 40, Tashkent
4538 Frost Mill, North Lisa
54212 Kyle Club Apt. 536, Fletcherfurt
Debraville 14-kv, dom 26, Tashkent
8384 Michael Knoll Suite 400, Jamesview
Apartment 20, West Briana district, Tashkent, UZ, 100038
Apartment 3, North David district, Tashkent, UZ, 100437
Apartment 41, North Eric district, Tashkent, UZ, 100515
Apartment 10, Michaelhaven district, Tashkent, UZ, 100000
0127 Salazar Hollow, Kimberlyfurt
Taylorstad 17-kv, dom 5, Tashkent
BROKEN,ADDRESS,DATA,,,
Ashleyfurt 26-kv, dom 22, Tashkent
98293 April Keys, New Timothyfurt

In [33]:
df1['addr']=df1['address_raw'].astype('str').apply(lambda x: x.split(', '))

In [34]:
df1['addr'].head(50)

0     [Apartment 37, South Kevin district, Tashkent,...
1                   [UZ 100332 Tashkent South Patricia]
2                   [Wendyshire 12-kv, dom 1, Tashkent]
3     [Apartment 16, North Tamara district, Tashkent...
4                              [BROKEN,ADDRESS,DATA,,,]
5     [Apartment 42, North Jamesfurt district, Tashk...
6              [Lake Tracishire 29-kv, dom 8, Tashkent]
7            [70576 Butler Harbor Suite 847, Janetberg]
8              [Williamsborough 2-kv, dom 18, Tashkent]
9                              [BROKEN,ADDRESS,DATA,,,]
10    [Apartment 34, North Samantha district, Tashke...
11    [Apartment 13, Morrismouth district, Tashkent,...
12                [Frankchester 9-kv, dom 20, Tashkent]
13                  [UZ 100394 Tashkent Stevensborough]
14                [Davidborough 9-kv, dom 29, Tashkent]
15              [1965 Jacobs Branch Apt. 418, Timburgh]
16                        [UZ 100399 Tashkent Joehaven]
17    [Apartment 22, Port Kevin district, Tashkent, ...
18                             [BROKEN,ADDRESS,DATA,,,]
19                  [Masontown 10-kv, dom 21, Tashkent]
20                             [BROKEN,ADDRESS,DATA,,,]
21                  [UZ 100063 Tashkent Lake Shaneland]
22           [0451 James Cliffs Suite 725, Wagnermouth]
23                 [0258 Sean Keys Apt. 380, Kevinfort]
24            [06462 Buck Springs Apt. 169, North Lisa]
25    [Apartment 20, Lake Crystal district, Tashkent...
26    [Apartment 27, South David district, Tashkent,...
27                             [BROKEN,ADDRESS,DATA,,,]
28                       [241 Sarah Spring, Bridgetton]
29            [Port Robertstad 16-kv, dom 50, Tashkent]
30                             [BROKEN,ADDRESS,DATA,,,]
31    [Apartment 42, Christineburgh district, Tashke...
32                [New Antonio 12-kv, dom 41, Tashkent]
33                [UZ 100883 Tashkent West Michaelport]
34                  [UZ 100652 Tashkent Lake Donaldton]
35                  [North Amy 11-kv, dom 49, Tashkent]
36    [Apartment 49, New Ian district, Tashkent, UZ,...
37    [Apartment 22, Youngton district, Tashkent, UZ...
38                    [UZ 100766 Tashkent Port William]
39          [73317 Timothy Port Suite 163, Dicksonbury]
40          [4613 Robert Cliff Suite 875, South Leslie]
41    [Apartment 17, Port Kristopherberg district, T...
42                    [UZ 100515 Tashkent North Joseph]
43                   [UZ 100297 Tashkent North Candace]
44                   [Annahaven 19-kv, dom 3, Tashkent]
45                             [BROKEN,ADDRESS,DATA,,,]
46                [UZ 100626 Tashkent East Williamport]
47            [6637 Michelle Unions Apt. 959, Erikfort]
48    [00607 Alvarez Circles Suite 553, North Benjamin]
49    [Apartment 28, East Andrew district, Tashkent,...
Name: addr, dtype: object

In [35]:
df1['addr_city']=df1['addr'].apply(lambda x: x[-3] if len(x)==5 else x[-1] if len(x)==3 else np.nan)

In [36]:
df1['addr_district']=df1['addr'].apply(lambda x: x[-4] if len(x)==5 else  np.nan)
df1['addr_postal']=df1['addr'].apply(lambda x: x[-1] if len(x)==5 and x[-1].isnumeric() else np.nan)
df1['addr_district'].isna().sum()

np.int64(797)

In [37]:
df['addr_city']=df1['addr_city']
df['addr_district']=df1['addr_district']
df['addr_postal']=df1['addr_postal']
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaT,Data Science,...,4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0,Tashkent,South Kevin district,100539
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,1.0,263.0,202.0,HP,2020.0,Samsung,2023.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0,Tashkent,North Tamara district,100097
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0,Tashkent,Laurenhaven district,100254
996,997,Scott Clark,20,NaN,NaN,+12050658737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,NaN,NaN
997,998,NaN,20,MALE,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0,Tashkent,New Brendan district,100394
998,999,Brittany Barrett,21,FEMALE,86.0,+16631181327,Port Rachael,NaN,NaT,data_sciense,...,3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0,NaN,NaN,NaN
999,1000,NaN,<NA>,NaN,NaN,+14867548735,Dariusborough,NaN,NaT,PYTHNO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Grossbury district,100222

**Step 7: Duplicate va missing data tekshirish**
   - Duplicate rowsni aniqlash va o‘chirish. 
   - Muhim columnlarda missing values mavjudligini aniqlash va qaror qabul qilish (fillna yoki dropna).

In [38]:

df.duplicated(['city', 'course', 'status', 'money_spent']).sum() # dublicate yo`q

np.int64(0)

In [39]:
import numpy as np
df.replace("", np.nan, inplace=True)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaT,Data Science,...,4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0,Tashkent,South Kevin district,100539
1,2,NaN,20,Female,NaN,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,1.0,263.0,202.0,HP,2020.0,Samsung,2023.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0,Tashkent,North Tamara district,100097
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0,Tashkent,Laurenhaven district,100254
996,997,Scott Clark,20,NaN,NaN,+12050658737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,NaN,NaN
997,998,NaN,20,MALE,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0,Tashkent,New Brendan district,100394
998,999,Brittany Barrett,21,FEMALE,86.0,+16631181327,Port Rachael,NaN,NaT,data_sciense,...,3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0,NaN,NaN,NaN
999,1000,NaN,<NA>,NaN,NaN,+14867548735,Dariusborough,NaN,NaT,PYTHNO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Grossbury district,100222

In [40]:
df.isna().sum()

student_id                0
name                    335
age                     226
gender                  219
score                   497
phone                   371
city                      0
email                   714
date_of_join            177
course                    0
attendance              326
status                    0
gpa                     299
remarks                 204
money_spent               0
event_time              161
address_raw               0
hobbies                 406
skills_tech_python      406
skills_tech_excel       406
skills_tech_sql         406
skills_soft             406
family_siblings         406
family_income_father    406
family_income_mother    406
laptop_brand            406
laptop_year             406
phone_brand             406
phone_year              406
addr_city               624
addr_district           797
addr_postal             797
dtype: int64

In [41]:
df_cleaned = df.dropna(how='all', subset=['score', 'hobbies', 'addr_district'], inplace=True)
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,NaN,NaN,+16193794152,Katieland,NaN,NaT,Data Science,...,4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0,Tashkent,South Kevin district,100539
2,3,Kathryn Moyer,20,NaN,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,1.0,263.0,202.0,HP,2020.0,Samsung,2023.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,<NA>,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0,Tashkent,North Tamara district,100097
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0,NaN,NaN,NaN
5,6,David Martinez,20,Male,NaN,+10748286016,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,North Jamesfurt district,100551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Kelly Martin,<NA>,male,NaN,NaN,Teresaville,NaN,2005-02-26 23:42:53,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Port Ashley district,100498
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0,Tashkent,Laurenhaven district,100254
997,998,NaN,20,MALE,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0,Tashkent,New Brendan district,100394
998,999,Brittany Barrett,21,FEMALE,86.0,+16631181327,Port Rachael,NaN,NaT,data_sciense,...,3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0,NaN,NaN,NaN
999,1000,NaN,<NA>,NaN,NaN,+14867548735,Dariusborough,NaN,NaT,PYTHNO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Grossbury district,100222

**Step 8: Data normalization**
  - Gender columnini standard formatga keltirish: Male / Female / Unknown. 
  - Course columnlarini yagona nomga keltirish: Data Science / Python / Other. 
  - Status columnlarini standart formatga keltirish (lower-case yoki uniform).

In [42]:
import numpy as np

df['gender'] = (
    df['gender']
    .astype(str)                # hammasini stringga o'tkazamiz
    .str.strip()                # bo'shliqlarni olib tashlaymiz
    .str.lower()                # lower case
)

df['gender'] = np.where(
    df['gender'].str.startswith('f'), 'Female',
    np.where(
        df['gender'].str.startswith('m'), 'Male',
        'Unknown'
    )
)

In [43]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,Unknown,NaN,+16193794152,Katieland,NaN,NaT,Data Science,...,4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0,Tashkent,South Kevin district,100539
2,3,Kathryn Moyer,20,Unknown,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,1.0,263.0,202.0,HP,2020.0,Samsung,2023.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,<NA>,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0,Tashkent,North Tamara district,100097
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0,NaN,NaN,NaN
5,6,David Martinez,20,Male,NaN,+10748286016,Hugheshaven,nathangibbs@hotmail.com,NaT,DATA SCIENCE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,North Jamesfurt district,100551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Kelly Martin,<NA>,Male,NaN,NaN,Teresaville,NaN,2005-02-26 23:42:53,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Port Ashley district,100498
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0,Tashkent,Laurenhaven district,100254
997,998,NaN,20,Male,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0,Tashkent,New Brendan district,100394
998,999,Brittany Barrett,21,Female,86.0,+16631181327,Port Rachael,NaN,NaT,data_sciense,...,3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0,NaN,NaN,NaN
999,1000,NaN,<NA>,Unknown,NaN,+14867548735,Dariusborough,NaN,NaT,PYTHNO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Grossbury district,100222

In [44]:
df['course']=(
    df['course']
    .astype(str)
    .str.strip()
    .str.lower()
)

In [45]:

df['course']=np.where(
    df['course'].str.startswith('d'), 'Data Science',
    np.where(
        df['course'].str.startswith('p'), 'Python',
        'Other'
    )
)

In [46]:
df['course'].head(50)

0     Data Science
2     Data Science
3     Data Science
4     Data Science
5     Data Science
6     Data Science
8     Data Science
9     Data Science
10    Data Science
11    Data Science
14          Python
15          Python
16    Data Science
17    Data Science
18    Data Science
19    Data Science
20    Data Science
21          Python
23    Data Science
24    Data Science
25    Data Science
26          Python
27          Python
28    Data Science
29    Data Science
31          Python
32    Data Science
33    Data Science
35          Python
36    Data Science
37    Data Science
39          Python
40    Data Science
41    Data Science
42    Data Science
43          Python
44    Data Science
45    Data Science
46    Data Science
47    Data Science
49    Data Science
50    Data Science
51    Data Science
52    Data Science
53    Data Science
54    Data Science
55          Python
57    Data Science
58    Data Science
60    Data Science
Name: course, dtype: str

In [47]:
df['status'].head(50)

0       active
2      pending
3     inactive
4      pending
5      pending
6       active
8       active
9     inactive
10      active
11    inactive
14     pending
15     pending
16      active
17    inactive
18      active
19     pending
20      active
21    inactive
23     pending
24     pending
25     pending
26    inactive
27    inactive
28    inactive
29     pending
31      active
32    inactive
33      active
35    inactive
36     pending
37      active
39    inactive
40      active
41    inactive
42     pending
43    inactive
44      active
45    inactive
46      active
47      active
49      active
50    inactive
51    inactive
52    inactive
53     pending
54    inactive
55    inactive
57     pending
58      active
60    inactive
Name: status, dtype: str

**Step 9: Final type conversion va export** 
  - Barcha columnlarning to‘g‘ri type da ekanligini tekshirish: string, int, float, datetime. 
  - Sanalarni yagona formatga keltirish (YYYY-MM-DD HH:MM:SS). 
  - Tozalangan data CSV faylga saqlash (super_dirty_students_cleaned.csv).

In [48]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,family_siblings,family_income_father,family_income_mother,laptop_brand,laptop_year,phone_brand,phone_year,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,Unknown,NaN,+16193794152,Katieland,NaN,NaT,Data Science,...,4.0,1198.0,1089.0,HP,2021.0,Xiaomi,2021.0,Tashkent,South Kevin district,100539
2,3,Kathryn Moyer,20,Unknown,NaN,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data Science,...,1.0,263.0,202.0,HP,2020.0,Samsung,2023.0,Tashkent,NaN,NaN
3,4,Ruben Wilson,<NA>,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data Science,...,4.0,508.0,698.0,Lenovo,2020.0,Samsung,2024.0,Tashkent,North Tamara district,100097
4,5,Robert Pruitt,20,Female,NaN,+11826595631,Kingburgh,NaN,2023-11-25 00:00:00,Data Science,...,3.0,862.0,1058.0,Lenovo,2023.0,Apple,2022.0,NaN,NaN,NaN
5,6,David Martinez,20,Male,NaN,+10748286016,Hugheshaven,nathangibbs@hotmail.com,NaT,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,North Jamesfurt district,100551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Kelly Martin,<NA>,Male,NaN,NaN,Teresaville,NaN,2005-02-26 23:42:53,Data Science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Port Ashley district,100498
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data Science,...,5.0,1382.0,1335.0,Dell,2017.0,Xiaomi,2019.0,Tashkent,Laurenhaven district,100254
997,998,NaN,20,Male,NaN,+12645778585,South Mary,NaN,2021-11-19 02:23:00,Data Science,...,5.0,1285.0,1005.0,HP,2020.0,Xiaomi,2024.0,Tashkent,New Brendan district,100394
998,999,Brittany Barrett,21,Female,86.0,+16631181327,Port Rachael,NaN,NaT,Data Science,...,3.0,541.0,571.0,Dell,2022.0,Samsung,2019.0,NaN,NaN,NaN
999,1000,NaN,<NA>,Unknown,NaN,+14867548735,Dariusborough,NaN,NaT,Python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tashkent,Grossbury district,100222

In [49]:
# saqlash
df.to_csv(
    "super_dirty_students_cleaned.csv",
    index=False,
    date_format="%Y-%m-%d %H:%M:%S"
)

Step 10: QA checks 
  - Original va cleaned row sonini solishtirish. 
   - Missing email va phone sonini tekshirish. 
  - Numeric columnlar (GPA, attendance, score) qiymatlari to‘g‘ri diapazonda ekanligini tekshirish. 
  - Duplicate rowlar yo‘qligini tasdiqlash.

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 835 entries, 0 to 999
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            835 non-null    int64
 1   name                  557 non-null    str
 2   age                   646 non-null    Int64
 3   gender                835 non-null    str
 4   score                 503 non-null    float64
 5   phone                 529 non-null    str
 6   city                  835 non-null    str
 7   email                 237 non-null    str
 8   date_of_join          684 non-null    datetime64[us]
 9   course                835 non-null    str
 10  attendance            563 non-null    Int64
 11  status                835 non-null    str
 12  gpa                   583 non-null    float64
 13  remarks               662 non-null    str
 14  money_spent           835 non-null    float64
 15  event_time            701 non-null    datetime64[us]
 16  address_raw           835 non-null    str
 17  hobbies               594 non-null    str
 18  skills_tech_python    594 non-null    float64
 19  skills_tech_excel     594 non-null    float64
 20  skills_tech_sql       594 non-null    float64
 21  skills_soft           594 non-null    str
 22  family_siblings       594 non-null    float64
 23  family_income_father  594 non-null    float64
 24  family_income_mother  594 non-null    float64
 25  laptop_brand          594 non-null    str
 26  laptop_year           594 non-null    float64
 27  phone_brand           594 non-null    str
 28  phone_year            594 non-null    float64
 29  addr_city             340 non-null    str
 30  addr_district         203 non-null    str
 31  addr_postal           203 non-null    str
dtypes: Int64(2), datetime64[us](2), float64(11), int64(1), str(16)
memory usage: 329.6 KB

In [51]:
df[['email', 'phone']].isna().sum()
df.duplicated().sum()

np.int64(0)

In [52]:
df[['gpa', 'score', 'attendance']].head(50)

      gpa  score  attendance
0    3.72    NaN        <NA>
2     NaN    NaN        <NA>
3    0.00   81.0        <NA>
4    4.37    NaN        <NA>
5   15.50    NaN         110
6    0.00   71.0        <NA>
8   15.50   77.0         110
9   37.00    NaN          99
10  37.00    NaN         110
11  -2.00   71.0         110
14  37.00   73.0         110
15  37.00    NaN         110
16    NaN   76.0         110
17    NaN   68.0         110
18   3.05   50.0         110
19    NaN    NaN          65
20  15.50   52.0         110
21    NaN   73.0          78
23  37.00   60.0         110
24  15.50    NaN        <NA>
25  15.50    NaN          96
26   1.18   59.0        <NA>
27    NaN   87.0         107
28    NaN   88.0        <NA>
29  37.00   69.0          64
31  -2.00    NaN         110
32  15.50   60.0          66
33  37.00    NaN          67
35  15.50   87.0         110
36    NaN    NaN         110
37    NaN    NaN          67
39    NaN   71.0         110
40  15.50    NaN        <NA>
41  -2.00    NaN          81
42  -2.00    NaN         110
43    NaN   93.0        <NA>
44   0.00   83.0         110
45  15.50    NaN          92
46  15.50   51.0        <NA>
47    NaN   95.0         110
49  37.00   90.0         110
50  37.00   61.0        <NA>
51  -2.00   63.0        <NA>
52  37.00   88.0         110
53    NaN   83.0        <NA>
54   0.00    NaN         110
55    NaN    NaN        <NA>
57  15.50   57.0          80
58    NaN   75.0        <NA>
60   3.20   93.0        <NA>

In [1]:
# Numeric columnlarni float ga o'tkazib olamiz
numeric_cols = ["gpa", "attendance", "score"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Range validation
invalid_gpa = df[(df["gpa"] < 0) | (df["gpa"] > 5)]
invalid_attendance = df[(df["attendance"] < 0) | (df["attendance"] > 100)]
invalid_score = df[(df["score"] < 0) | (df["score"] > 100)]

print("Invalid GPA rows:", len(invalid_gpa))
print("Invalid attendance rows:", len(invalid_attendance))
print("Invalid score rows:", len(invalid_score))

NameError: name 'pd' is not defined